name: gosum

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/gosum.yml'
      - 'go.mod'
      - 'go.sum'

jobs:
  fix:
    uses: jozrk/.github/.github/workflows/app-gosum.yml@master
